services:
  server:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    env_file:
      - ./env/server.env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl.sh || exit 0"]
      interval: 10s
      timeout: 10s
      retries: 10
  db:
    container_name: postgresql
    image: postgres:16.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./env/db.env
    ports:
      - 5432:5432
  pg_admin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
volumes:
  db_schema:
